services:
 db:
  image: postgres:16.3-bullseye
  restart: always
  ports: 
      - "5432:5432"
  volumes: 
      - volume_postgres:/var/lib/postgres/data
  environment:
   POSTGRES_USER: "postgres"
   POSTGRES_PASSWORD: "postgres"
   
 pgadmin: 
  image: dpage/pgadmin4:6.11
  ports:
      - 18080:80
  volumes:
      - volume_pgadmin:/var/lib/pgadmin
  environment:
   PGADMIN_DEFAULT_EMAIL: example@example.com
   PGADMIN_DEFAULT_PASSWORD: password
      
volumes:
  volume_postgres:
    name: vpg
  volume_pgadmin:
    name: vpga